# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build_mac_java_x86:
    name: JAVA Mac x86_64
    timeout-minutes: 30
    runs-on: macos-14
    steps:
    - name: Install common dependencies
      run: |
        pip install trimesh pytest maven
    - name: Build googletest for x86_64
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build && cd build
        cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release ..
        make
        sudo make install
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build
      run: |
        bash bindings/java/scripts/macos/buildC.sh
    - name: Upload native libraries
      uses: actions/upload-artifact@v4
      with:
        name: native-libs-mac-x86_64
        path: bindings/java/src/main/resources/manifold3d/natives/
  build_mac_java:
    name: JAVA Mac arm64
    timeout-minutes: 30
    runs-on: macos-14
    steps:
    - name: Install common dependencies
      run: |
        pip install trimesh pytest maven
    - name: Build googletest for arm64
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build && cd build
        cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_BUILD_TYPE=Release ..
        make
        sudo make install
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build
      run: |
        bash bindings/java/scripts/macos/buildC-arm.sh
    - name: Upload native libraries
      uses: actions/upload-artifact@v4
      with:
        name: native-libs-mac-arm64
        path: bindings/java/src/main/resources/manifold3d/natives/
  build_linux_java_ARM:
    name: JAVA Linux_ARM Build
    timeout-minutes: 45
    runs-on: ubuntu-24.04-arm
    env:
      CC: gcc-14
      CXX: g++-14
    steps:
    - uses: actions/checkout@v6
    - uses: lukka/get-cmake@v4.2.3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.6.0
      with:
        packages: libgtest-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev
    - run: pip install -U trimesh pytest
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build With parallelization
      run: |
         bash bindings/java/scripts/linux/buildC-arm.sh
    - name: Upload native libraries
      uses: actions/upload-artifact@v4
      with:
        name: native-libs-linux-arm64
        path: bindings/java/src/main/resources/manifold3d/natives/
  build_linux_java_x86:
    name: JAVA Linux_x86 Build
    timeout-minutes: 45
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04
      options: --user root
    env:
      CC: gcc
      CXX: g++
    steps:
    - run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
            unzip \
            curl \
            wget \
            ca-certificates \
            lsb-release \
            gnupg \
            git \
            file \
            xz-utils \
            openjdk-11-jdk \
            gcc \
            g++ \
            make \
            maven
    - uses: actions/checkout@v6
    - uses: lukka/get-cmake@v4.2.3
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.6.0
      with:
        packages: libgtest-dev libtbb-dev pkg-config 
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build With parallelization
      run: |
        bash bindings/java/scripts/linux/buildC.sh
    - name: Upload native libraries
      uses: actions/upload-artifact@v4
      with:
        name: native-libs-linux-x86
        path: bindings/java/src/main/resources/manifold3d/natives/
  deploy_java:
      name: JAVA Deploy Jar to Clojars
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/')
      needs: [build_mac_java_x86, build_linux_java_x86, build_linux_java_ARM, build_mac_java]
      steps:
      - uses: actions/checkout@v4
      - name: Download native libraries
        uses: actions/download-artifact@v4
        with:
          name: native-libs-mac-x86_64
          path: bindings/java/src/main/resources/manifold3d/natives/
      - name: Download native libraries
        uses: actions/download-artifact@v4
        with:
          name: native-libs-mac-arm64
          path: bindings/java/src/main/resources/manifold3d/natives/
      - name: Download native libraries
        uses: actions/download-artifact@v4
        with:
          name: native-libs-linux-arm64
          path: bindings/java/src/main/resources/manifold3d/natives/
      - name: Download native libraries
        uses: actions/download-artifact@v4
        with:
          name: native-libs-linux-x86
          path: bindings/java/src/main/resources/manifold3d/natives/
      - name: List shared libraries
        run: |
          ls -al bindings/java/src/main/resources/manifold3d/natives/
          ls -al bindings/java/src/main/resources/manifold3d/natives/linux-x86_64
          ls -al bindings/java/src/main/resources/manifold3d/natives/linux-arm64
          ls -al bindings/java/src/main/resources/manifold3d/natives/mac-arm64
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install Maven 3.8.7
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
          tar -xzf apache-maven-3.8.7-bin.tar.gz
          echo "$PWD/apache-maven-3.8.7/bin" >> $GITHUB_PATH
      - name: Check Maven version
        run: mvn --version
      - name: Build Jar
        run: |
          bash bindings/java/scripts/findVersion.sh
          ls -al bindings/java/scripts/
          bash bindings/java/scripts/clojar.sh $(bash bindings/java/scripts/findVersion.sh)
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bindings/java/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
