name: JitPack

on:
  repository_dispatch:
    types: trim-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@v4.2.3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ make wget unzip libgtest-dev

      - name: Download JDK
        run: |
          wget https://cdn.azul.com/zulu/bin/zulu25.32.21-ca-fx-jdk25.0.2-linux_x64.tar.gz
          tar -xzf zulu25.32.21-ca-fx-jdk25.0.2-linux_x64.tar.gz

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 25
          jdkFile: ./zulu25.32.21-ca-fx-jdk25.0.2-linux_x64.tar.gz

      - name: Build native libraries (without Maven test)
        run: |
          git clone https://github.com/AngusJohnson/Clipper2.git clipper2
          cd clipper2 && git checkout 46f639177fe418f9689e8ddb74f08a870c71f5b4 && cd ..
          git clone https://github.com/wjakob/nanobind.git nanobind
          cd nanobind && git checkout v2.12.0 && cd ..

          mkdir build && cd build
          cmake -DMANIFOLD_CROSS_SECTION=ON -DMANIFOLD_USE_BUILTIN_CLIPPER2=ON \
            -DCMAKE_BUILD_TYPE=Release -DASSIMP_ENABLE=OFF -DBUILD_SHARED_LIBS=ON \
            -DMANIFOLD_DEBUG=OFF -DMANIFOLD_ASSERT=OFF -DMANIFOLD_TEST=OFF \
            -DMANIFOLD_EXTRAS=ON -DMANIFOLD_EXPORT=OFF -DMANIFOLD_PAR=ON \
            -DMANIFOLD_USE_BUILTIN_TBB=ON \
            -DFETCHCONTENT_SOURCE_DIR_CLIPPER2=../clipper2 \
            -DFETCHCONTENT_SOURCE_DIR_NANOBIND=../nanobind \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_RPATH='$ORIGIN' ..
          make
          cd ..

          mkdir -p bindings/java/src/main/resources/manifold3d/natives/linux-x86_64/
          cp build/src/libmanifold.so bindings/java/src/main/resources/manifold3d/natives/linux-x86_64/
          ln -sf libmanifold.so bindings/java/src/main/resources/manifold3d/natives/linux-x86_64/libmanifold.so.3
          cp build/bindings/c/libmanifoldc.so bindings/java/src/main/resources/manifold3d/natives/linux-x86_64/
          ln -sf libmanifoldc.so bindings/java/src/main/resources/manifold3d/natives/linux-x86_64/libmanifoldc.so.3

      - name: Build Java bindings with Gradle
        working-directory: bindings/java
        run: |
          chmod +x ./gradlew
          ./gradlew jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jitpack
          path: bindings/java/build/libs/*.jar
